# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Test and Pack

on:
  pull_request:
    branches: 
        - main

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Dependencies
        run: npm ci
      # - name: Run Tests
      #   run: npm test

  Pack:
    needs: BuildAndTest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com/
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
            versionSpec: '5.x'
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
      - name: Install Dependencies
        run: npm ci
      - name: Configure npm credentials
        run: |
          echo @peteatkinson:https://npm.pkg.github.com/ > ./.npmrc 
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> ./.npmrc
      - name: Setup Version
        run: npm version ${{ steps.gitversion.outputs.SemVer }} --force
      - name: Publish NPM Package
        run: npm publish
        working-directory: ./
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
